### ISSUE TITLE
TypeError: Cannot read property 'created' of undefined  at controllers.js:188

### ISSUE THREAD

**Issue by kishandas** [arjunsk/ionic-shopping-cart-2#2]
When i click on signup button this error occurs. Please help me out this.

**Comment by arjunsk** [comment]
Please find the latest ionic cart https://github.com/arjunsk/ionic-shopping-cart-2

If you found it useful,
make sure to star it and follow me via git hub.

**Comment by kishandas** [comment]
I,m using the latest ionic shopping cart 2.
Till this error occurs.

**Comment by arjunsk** [comment]
Can we chat in hangouts ?

**Comment by kishandas** [comment]
After some hours we can chat on hangout

**Comment by kishandas** [comment]
Can you make a video of ionic shopping cart 2 .
